<?php 

// Database Constants

$HOST             =     "localhost";
$DB            =    "testing";
$WEBUSER        =    "root";
$WEBPASSWORD        =    "";

// Colour Constants

$COLOR_PRIMARY        =    "#037B0B";
$COLOR_SECONDARY    =    "#FFFFC0";
$COLOR_TERTIARY        =    "#ECED81";

// Value Constants

$TRUE            =    1;
$FALSE            =    0;
    
// Application Specific
$TITLE            =    "Object Orientation Demonstration";
$ADMINEMAIL        =    "webmaster@domin.com";
    
// CSS Plug-in Values
    
$CSSBOXTITLE        =     "boxtitle";
    
?>
