<?php 
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
"http://www.w3.org/TR/html4/loose.dtd"> 
<html> 
<head> 
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
<title>Help: Request Password</title> 

<style type="text/css"> 
<!-- 
body { 
    font-family: Arial, Helvetica, sans-serif; 
    text-align:center; 
} 
p { 
    font-size: 14px; 
    line-height: 20px; 
} 
#main { 
    width:550px; 
    margin:0 auto; 
    padding:10px; 
    text-align:left; 
    border: 1px solid #000000; 
} 
--> 
</style> 
</head> 

<body onLoad="javascript:window.resizeTo(625,600);return false;"> 
<div id="main"> 
  <h2 style="text-align:center;margin-top:10px;">Help: Request Password </h2> 
<br><br>
A User's password is encrypted within the system and can not be read at any time by any one.  Because of this fact, a password can not be retrieved if the user forgets their own password.  The only way to change the password is to have a new password generated by the system.<br><br>This is done be selecting "Can't remember your password - <b>Click Here</b>" from the main login.<br><br>The user will be prompted for their employee ID.  On submit, the system will generate a new password for the user.  This password will be emailed to the user during the system's normal email cycle (approximately every 15-20 minutes).<br><br>If the password is not received, via email, in this timeframe, please contact your Admin.  This may signify that there is not an email address specified for the given user, or that the email address is incorrect.  Once the new password has been received the user may change the password to something more memorable using the <b>Admin/Change Password</b> menu option.


</div>   
<br><br>
<input class="gray" type="Button" name="WINDOWCLOSE" value="Window Close" onclick="javascript:window.close()">&nbsp;

</body> 
</html> 
